# -*- coding: utf-8 -*-
"""pleaserun!!!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlyW0KETE7ch963s3fY6pedRHDs1TtQ-

#Named Entity Recognition on News Text

1. Project Introduction
2. Install & Import Libraries
3. Load Kaggle Dataset
4. Combine Multiple Files
5. Dataset Exploration
6. Data Cleaning
7. Text Preprocessing
8. spaCy NER
9. BERT NER
10. Entity Analysis
11. Manual Evaluation Subset
12. Generate spaCy Predictions
13. Human Verification & Ground Truth Creation
14. Precision, Recall & F1 Evaluation
15. spaCy vs BERT Comparison
16. Explainability Analysis
17. Bias / Performance Audit
18. Error Analysis
19. Visualizations
20. Conclusion

# **1.Project Introduction**
# Named Entity Recognition on News Text

## Project Overview

This project focuses on automatically identifying and classifying named entities
from news text using Natural Language Processing (NLP).

The project compares two approaches:

1. spaCy-based Named Entity Recognition
2. BERT-based Named Entity Recognition

The models are evaluated using Precision, Recall and F1-Score.

The project also includes:
- Entity-wise performance analysis
- Bias/performance audit
- Explainability analysis
- Error analysis

# **2. Installing & Importing Libraries**
"""



import sys
import re
# Safety monkeypatch for Windows Application Control blocking C extension _regex.pyd
sys.modules.setdefault("regex", re)
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
from pathlib import Path


# Safe display function for running in standard terminal or notebook
try:
    display  # type: ignore
except NameError:
    def display(x):
        print(x)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import spacy
try:
    from datasets import load_dataset
except ImportError:
    load_dataset = None
from transformers import pipeline
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)


import warnings
warnings.filterwarnings("ignore")
import os
import glob


"""# **3. Load Kaggle Dataset**"""

# Resolve dataset directory dynamically with fallbacks
_script_dir = Path(__file__).resolve().parent if "__file__" in globals() else Path(".")
_candidate_paths = [
    _script_dir.parent / "datasets",
    Path("datasets"),
    Path("/content"),
]
DATA_PATH = next((p for p in _candidate_paths if p.is_dir()), Path("datasets"))

print(f"Using dataset path: {DATA_PATH}")
for root, dirs, files in os.walk(DATA_PATH):
    for file in files:
        print(os.path.join(root, file))

"""# **4. Combine Multiple Files**"""

DATA_FILES = [
    "business_data.csv",
    "education_data.csv",
    "entertainment_data.csv",
    "sports_data.csv",
    "technology_data.csv"
]

news_files = [str(DATA_PATH / f) for f in DATA_FILES if (DATA_PATH / f).is_file()]

print("News files found:")
for file in news_files:
    print(os.path.basename(file))

dataframes = []

for file in news_files:
    try:
        # Load CSV with natural headers and clean column names
        df = pd.read_csv(file, on_bad_lines='skip')
        df.columns = [str(col).strip().lower() for col in df.columns]
        
        # Standardize expected columns
        if 'content' in df.columns:
            df['Content'] = df['content'].fillna("").astype(str).str.strip()
        if 'category' in df.columns:
            df['Category'] = df['category'].fillna("Uncategorized").astype(str).str.strip()
        if 'headlines' in df.columns:
            df['Headlines'] = df['headlines'].fillna("").astype(str).str.strip()
        if 'description' in df.columns:
            df['Description'] = df['description'].fillna("").astype(str).str.strip()
        if 'url' in df.columns:
            df['URL'] = df['url'].fillna("").astype(str).str.strip()

        print(
            os.path.basename(file),
            "->",
            df.shape
        )

        dataframes.append(df)
    except Exception as e:
        print(f"Could not read file {os.path.basename(file)} due to error: {e}")

news_df = pd.concat(
    dataframes,
    ignore_index=True
)

# Clean up empty content rows
news_df = news_df[news_df['Content'].ne("") & (news_df['Category'] != 'category')].reset_index(drop=True)

print("\nFinal dataset shape:", news_df.shape)

"""# **5. Dataset Exploration**"""

# Checking column count
print(news_df.columns.tolist())

news_df.head()

news_df.info()

print("Rows:", news_df.shape[0])
print("Columns:", news_df.shape[1])

"""# **6. Data Cleaning**"""

# Calculate missing values
missing_count = news_df.isnull().sum()
# Keep only columns with missing values
missing_count = missing_count[missing_count > 0]
# Calculate missing percentage
missing_percent = (
    missing_count / len(news_df)
) * 100
# Create a DataFrame
missing_df = pd.DataFrame({
    "Column": missing_count.index,
    "Missing Values": missing_count.values,
    "Missing Percentage": missing_percent.values
})
# Sort from highest to lowest
missing_df = missing_df.sort_values(
    "Missing Percentage",
    ascending=False
)

missing_df

"""# **7. Text Preprocessing**"""

# Remove Articles Without Content
news_df = news_df.dropna(
    subset=["Content"]
).copy()

news_df = news_df.reset_index(drop=True)

print("Dataset after removing missing content:")
print(news_df.shape)

# Remove Duplicate Articles
duplicates = news_df["Content"].duplicated().sum()

print("Duplicate articles:", duplicates)

news_df = news_df.drop_duplicates(
    subset=["Content"]
).reset_index(drop=True)

print("Dataset after removing duplicates:")
print(news_df.shape)

# Category Distribution
print(
    news_df["Category"].value_counts()
)

plt.figure(figsize=(9, 5))

sns.countplot(
    data=news_df,
    x="Category",
    order=news_df["Category"].value_counts().index
)

plt.title("News Articles by Category")
plt.xlabel("Category")
plt.ylabel("Number of Articles")
plt.xticks(rotation=45)

plt.show()

import re

# Text Cleaning
def clean_text(text):

    text = str(text)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove leading/trailing spaces
    text = text.strip()

    return text

news_df["Clean_Content"] = (

    news_df["Content"]
    .apply(clean_text)
)

news_df[
    ["Content", "Clean_Content"]
].head()

# Text Length Analysis
news_df["Word_Count"] = (
    news_df["Clean_Content"]
    .str.split()
    .str.len()
)
news_df["Word_Count"].describe()

plt.figure(figsize=(9, 5))

sns.histplot(
    news_df["Word_Count"],
    bins=50
)

plt.title("Distribution of Article Length")
plt.xlabel("Number of Words")
plt.ylabel("Number of Articles")

plt.show()

# Sentence Segmentation
nlp = spacy.load("en_core_web_sm")
sample_text = news_df["Clean_Content"].iloc[0]

doc = nlp(sample_text)

sentences = [
    sent.text
    for sent in doc.sents
]

print("Number of sentences:", len(sentences))

for sentence in sentences[:5]:
    print(sentence)

"""# **8. spaCy NER**"""

nlp = spacy.load("en_core_web_sm")

test_text = """
Narendra Modi visited Mumbai on Monday.
"""

doc = nlp(test_text)

for ent in doc.ents:
    print(ent.text, "->", ent.label_)

#creating label mapping so that we have consistent labels across spaCy, BERT and manual Evaluation
label_mapping = {

    "PERSON": "PERSON",
    "PER": "PERSON",

    "ORG": "ORG",

    "GPE": "LOCATION",
    "LOC": "LOCATION",
    "LOCATION": "LOCATION",

    "DATE": "DATE",

    "MONEY": "MONEY",

    "EVENT": "EVENT",

    "MISC": "MISC"
}

def extract_spacy_entities(text):

    doc = nlp(text)

    entities = []

    for ent in doc.ents:

        label = label_mapping.get(
            ent.label_,
            ent.label_
        )

        entities.append({
            "text": ent.text,
            "label": label,
            "start": ent.start_char,
            "end": ent.end_char
        })

    return entities

sample_text = """
Narendra Modi visited New Delhi on Monday
to meet representatives of the United Nations.
"""

spacy_results = extract_spacy_entities(
    sample_text
)

for entity in spacy_results:
    print(
        entity["text"],
        "->",
        entity["label"]
    )

from spacy import displacy

doc = nlp(sample_text)

displacy.render(
    doc,
    style="ent",
    jupyter=True
)

"""# **9. BERT based NER**"""

bert_ner = pipeline(
    "ner",
    model="dslim/bert-base-NER",
    aggregation_strategy="simple"
)

sample_text = """
Narendra Modi visited New Delhi on Monday
and met representatives of the United Nations.
"""

bert_results = bert_ner(sample_text)

for result in bert_results:

    print(
        result["word"],
        "->",
        result["entity_group"],
        "->",
        round(result["score"], 3)
    )

def extract_bert_entities(text):

    # Truncate to safe token boundary for BERT
    clean_input = str(text)[:1000]
    results = bert_ner(clean_input)

    entities = []

    for result in results:
        w = str(result.get("word", "")).strip()
        score = float(result.get("score", 1.0))
        label = result.get("entity_group", "MISC")

        # Merge subword tokens (e.g. ##ren, ##dra)
        if w.startswith("##") and entities and entities[-1]["label"] == label:
            entities[-1]["text"] += w[2:]
            entities[-1]["end"] = int(result["end"])
            entities[-1]["score"] = round((entities[-1]["score"] + score) / 2, 4)
        else:
            clean_word = w.lstrip("#").strip()
            if clean_word:
                entities.append({
                    "text": clean_word,
                    "label": label,
                    "score": round(score, 4),
                    "start": int(result["start"]),
                    "end": int(result["end"])
                })

    return entities


extract_bert_entities(sample_text)

for entity in extract_bert_entities(sample_text):

    print(
        entity["text"],
        "->",
        entity["label"],
        "->",
        round(entity["score"], 3)
    )

"""# **10. Entity Analysis**"""

bert_entities = extract_bert_entities(
    sample_text
)

for entity in bert_entities:

    print(
        f"{entity['text']} -> "
        f"{entity['label']} -> "
        f"{entity['score']:.3f}"
    )

bert_entities_all = []

sample_articles = news_df[
    "Clean_Content"
].head(25)


from tqdm.auto import tqdm

for article in tqdm(
    sample_articles,
    desc="Processing BERT NER"
):

    try:
        entities = extract_bert_entities(
            article
        )

        bert_entities_all.extend(
            entities
        )

    except Exception as e:
        print("Error:", e)

bert_label_counts = pd.Series([
    entity["label"]
    for entity in bert_entities_all
]).value_counts()

print(bert_label_counts)

plt.figure(figsize=(9, 5))

sns.barplot(
    x=bert_label_counts.index,
    y=bert_label_counts.values
)

plt.title("Entity Distribution Using BERT")
plt.xlabel("Entity Type")
plt.ylabel("Number of Entities")

plt.show()

bert_confidence_df = pd.DataFrame(
    bert_entities_all
)

bert_confidence = (
    bert_confidence_df
    .groupby("label")["score"]
    .mean()
    .sort_values(ascending=False)
)

print(bert_confidence)

plt.figure(figsize=(9, 5))

sns.barplot(
    x=bert_confidence.index,
    y=bert_confidence.values
)

plt.title("Average BERT Confidence by Entity Type")
plt.xlabel("Entity Type")
plt.ylabel("Average Confidence")
plt.ylim(0, 1)

plt.show()

"""# **11. Manual Evaluation Subset**"""

annotation_df = news_df[
    ["Content", "Category"]
].sample(
    20,
    random_state=42
).reset_index(drop=True)

annotation_df.insert(
    0,
    "Article_ID",
    range(1, 21)
)

annotation_df["Annotation_Text"] = (
    annotation_df["Content"]
    .astype(str)
    .str[:3000]
)

print(
    "Number of articles:",
    len(annotation_df)
)

print(
    "Characters per article:",
    annotation_df["Annotation_Text"]
    .str.len()
    .describe()
)

"""# **12. Generate spaCy Predictions**"""

def get_spacy_suggestions(text):

    entities = extract_spacy_entities(text)

    suggestions = []

    for entity in entities:

        suggestions.append(
            f"{entity['text']}|{entity['label']}"
        )

    return ";".join(suggestions)

tqdm.pandas()

annotation_df["Suggested_Entities"] = (
    annotation_df["Annotation_Text"]
    .progress_apply(
        get_spacy_suggestions
    )
)

"""# **13. Human Verification & Ground Truth Creation**
The selected Kaggle news dataset does not contain predefined Named Entity Recognition (NER)
labels. Therefore, there is no ground truth available to directly measure how accurately
spaCy and BERT identify entities.

To create a manageable evaluation dataset, 20 news articles are randomly selected and only
the first 3,000 characters of each article are used. This provides enough text and named
entities for evaluation while keeping the manual verification process practical.

First, spaCy NER is applied to these 20 article samples to automatically generate candidate
entity predictions. Instead of manually identifying every entity from scratch, these
predictions are reviewed by a human. Incorrect entities are corrected, missing entities are
added, and wrongly classified entities are changed to the appropriate category.

The corrected annotations are then treated as the ground truth, which represents the expected
correct entities for the selected text.

Finally, the predictions produced by spaCy and BERT are compared with this ground truth.
This allows us to calculate Precision, Recall, and F1-Score and quantitatively evaluate the
performance of both NER models.
"""

annotation_df["Manual_Entities"] = ""

display(
    annotation_df[
        [
            "Article_ID",
            "Category",
            "Suggested_Entities",
            "Manual_Entities"
        ]
    ]
)

workbook_candidates = [
    DATA_PATH / "NER_Annotation_Workbook.xlsx",
    Path("datasets/NER_Annotation_Workbook.xlsx"),
    Path("NER_Annotation_Workbook.xlsx"),
]
wb_path = next((p for p in workbook_candidates if p.is_file()), Path("NER_Annotation_Workbook.xlsx"))
annotation_df = pd.read_excel(wb_path)

print(
    annotation_df.columns.tolist()
)

print(
    annotation_df[
        [
            "Article_ID",
            "Manual_Entities"
        ]
    ].head(10)
)

filled_annotations = (
    annotation_df["Manual_Entities"]
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(
    "Articles with manual annotations:",
    filled_annotations,
    "out of",
    len(annotation_df)
)

def parse_manual_entities(entity_string):

    if pd.isna(entity_string):
        return []

    entity_string = str(
        entity_string
    ).strip()

    if entity_string == "":
        return []

    entities = []

    parts = entity_string.split(";")

    for part in parts:

        part = part.strip()

        if "|" not in part:
            continue

        entity_text, entity_label = (
            part.rsplit("|", 1)
        )

        entity_text = entity_text.strip()
        entity_label = entity_label.strip().upper()

        if entity_text and entity_label:

            entities.append({
                "text": entity_text,
                "label": entity_label
            })

    return entities

test_annotation = (
    "Narendra Modi|PERSON;"
    "Mumbai|LOCATION;"
    "Monday|DATE"
)

print(
    parse_manual_entities(
        test_annotation
    )
)

label_mapping = {
    "PERSON": "PERSON",
    "PER": "PERSON",

    "ORG": "ORG",

    "GPE": "LOCATION",
    "LOC": "LOCATION",
    "LOCATION": "LOCATION",

    "DATE": "DATE",

    "MONEY": "MONEY",

    "EVENT": "EVENT",

    "MISC": "MISC",
    "CARDINAL": "CARDINAL",
    "ORDINAL": "ORDINAL",
    "WORK_OF_ART": "WORK_OF_ART"
}

def normalize_label(label):

    return label_mapping.get(
        label.upper(),
        label.upper()
    )

def create_entity_set(entities):

    entity_set = set()

    for entity in entities:

        text = (
            entity["text"]
            .strip()
            .lower()
        )

        label = normalize_label(
            entity["label"]
        )

        entity_set.add(
            (text, label)
        )

    return entity_set

"""# **14. Precision, Recall & F1 Evaluation**"""


true_entities_spacy = set()
pred_entities_spacy = set()

for _, row in annotation_df.iterrows():

    # Human ground truth
    manual_entities = (
        parse_manual_entities(
            row["Manual_Entities"]
        )
    )

    # spaCy predictions
    predicted_entities = (
        extract_spacy_entities(
            row["Annotation_Text"]
        )
    )

    true_entities_spacy.update(
        create_entity_set(
            manual_entities
        )
    )

    pred_entities_spacy.update(
        create_entity_set(
            predicted_entities
        )
    )

tp_spacy = len(
    true_entities_spacy &
    pred_entities_spacy
)

fp_spacy = len(
    pred_entities_spacy -
    true_entities_spacy
)

fn_spacy = len(
    true_entities_spacy -
    pred_entities_spacy
)

precision_spacy = (
    tp_spacy /
    (tp_spacy + fp_spacy)
    if (tp_spacy + fp_spacy) > 0
    else 0
)

recall_spacy = (
    tp_spacy /
    (tp_spacy + fn_spacy)
    if (tp_spacy + fn_spacy) > 0
    else 0
)

f1_spacy = (
    2 * precision_spacy * recall_spacy /
    (precision_spacy + recall_spacy)
    if (precision_spacy + recall_spacy) > 0
    else 0
)

print("========== spaCy ==========")
print("True Positives :", tp_spacy)
print("False Positives:", fp_spacy)
print("False Negatives:", fn_spacy)
print()
print("Precision:", round(precision_spacy, 3))
print("Recall   :", round(recall_spacy, 3))
print("F1 Score :", round(f1_spacy, 3))

true_entities_bert = set()
pred_entities_bert = set()

for _, row in tqdm(
    annotation_df.iterrows(),
    total=len(annotation_df),
    desc="Running BERT evaluation"
):

    # Ground truth
    manual_entities = (
        parse_manual_entities(
            row["Manual_Entities"]
        )
    )

    # BERT prediction
    predicted_entities = (
        extract_bert_entities(
            row["Annotation_Text"]
        )
    )

    true_entities_bert.update(
        create_entity_set(
            manual_entities
        )
    )

    pred_entities_bert.update(
        create_entity_set(
            predicted_entities
        )
    )

tp_bert = len(
    true_entities_bert &
    pred_entities_bert
)

fp_bert = len(
    pred_entities_bert -
    true_entities_bert
)

fn_bert = len(
    true_entities_bert -
    pred_entities_bert
)

precision_bert = (
    tp_bert /
    (tp_bert + fp_bert)
    if (tp_bert + fp_bert) > 0
    else 0
)

recall_bert = (
    tp_bert /
    (tp_bert + fn_bert)
    if (tp_bert + fn_bert) > 0
    else 0
)

f1_bert = (
    2 * precision_bert * recall_bert /
    (precision_bert + recall_bert)
    if (precision_bert + recall_bert) > 0
    else 0
)

print("========== BERT ==========")
print("True Positives :", tp_bert)
print("False Positives:", fp_bert)
print("False Negatives:", fn_bert)
print()
print("Precision:", round(precision_bert, 3))
print("Recall   :", round(recall_bert, 3))
print("F1 Score :", round(f1_bert, 3))

"""# **15. SpaCy vs BERT Comparison**"""

final_results = pd.DataFrame({

    "Model": [
        "spaCy",
        "BERT"
    ],

    "Precision": [
        precision_spacy,
        precision_bert
    ],

    "Recall": [
        recall_spacy,
        recall_bert
    ],

    "F1 Score": [
        f1_spacy,
        f1_bert
    ]
})

final_results[
    ["Precision", "Recall", "F1 Score"]
] = final_results[
    ["Precision", "Recall", "F1 Score"]
].round(3)

display(final_results)

plot_df = final_results.melt(
    id_vars="Model",
    var_name="Metric",
    value_name="Score"
)

plt.figure(figsize=(9, 5))

sns.barplot(
    data=plot_df,
    x="Metric",
    y="Score",
    hue="Model"
)

plt.title(
    "spaCy vs BERT NER Performance"
)

plt.xlabel("Evaluation Metric")
plt.ylabel("Score")

plt.ylim(0, 1)

plt.tight_layout()
plt.show()

"""# **16. Explainability Analysis**"""

spacy_entities_all = []

for text in tqdm(
    news_df["Clean_Content"].head(100),
    desc="Analyzing spaCy entities"
):


    entities = extract_spacy_entities(text)

    spacy_entities_all.extend(
        entities
    )

spacy_entity_df = pd.DataFrame(
    spacy_entities_all
)

spacy_counts = (
    spacy_entity_df["label"]
    .value_counts()
)

display(spacy_counts)

plt.figure(figsize=(9, 5))

sns.barplot(
    x=spacy_counts.index,
    y=spacy_counts.values
)

plt.title(
    "Entity Distribution Using spaCy"
)

plt.xlabel("Entity Type")
plt.ylabel("Number of Entities")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

bert_entities_all = []

for text in tqdm(
    news_df["Clean_Content"].head(500),
    desc="Analyzing BERT entities"
):

    try:

        entities = extract_bert_entities(
            text
        )

        bert_entities_all.extend(
            entities
        )

    except Exception as e:

        print(
            "Error:",
            e
        )

bert_entity_df = pd.DataFrame(
    bert_entities_all
)

display(
    bert_entity_df.head()
)

bert_counts = (
    bert_entity_df["label"]
    .value_counts()
)

display(bert_counts)

plt.figure(figsize=(9, 5))

sns.barplot(
    x=bert_counts.index,
    y=bert_counts.values
)

plt.title(
    "Entity Distribution Using BERT"
)

plt.xlabel("Entity Type")
plt.ylabel("Number of Entities")

plt.tight_layout()
plt.show()

confidence_by_type = (
    bert_entity_df
    .groupby("label")["score"]
    .mean()
    .sort_values(
        ascending=False
    )
)

display(
    confidence_by_type
)

plt.figure(figsize=(9, 5))

sns.barplot(
    x=confidence_by_type.index,
    y=confidence_by_type.values
)

plt.title(
    "Average BERT Confidence by Entity Type"
)

plt.xlabel("Entity Type")
plt.ylabel("Average Confidence")

plt.ylim(0, 1)

plt.tight_layout()
plt.show()

high_confidence = (
    bert_entity_df
    .sort_values(
        "score",
        ascending=False
    )
    .head(10)
)

display(
    high_confidence[
        ["text", "label", "score"]
    ]
)

low_confidence = (
    bert_entity_df
    .sort_values(
        "score",
        ascending=True
    )
    .head(10)
)

display(
    low_confidence[
        ["text", "label", "score"]
    ]
)

"""# **17. Bias / Performance Audit**"""

audit_counts = pd.DataFrame({
    "spaCy": spacy_counts,
    "BERT": bert_counts
}).fillna(0)

display(audit_counts)

category_entities = []

for _, row in tqdm(
    news_df.head(1000).iterrows(),
    total=min(1000, len(news_df)),
    desc="Category audit"
):

    entities = extract_spacy_entities(
        row["Clean_Content"]
    )

    for entity in entities:

        category_entities.append({

            "Category": row["Category"],

            "Entity": entity["text"],

            "Label": entity["label"]
        })

category_entity_df = pd.DataFrame(
    category_entities
)

category_label_counts = pd.crosstab(
    category_entity_df["Category"],
    category_entity_df["Label"]
)

display(category_label_counts)

plt.figure(figsize=(12, 6))

sns.heatmap(
    category_label_counts,
    annot=True,
    fmt="d"
)

plt.title(
    "Named Entity Distribution Across News Categories"
)

plt.xlabel("Entity Type")
plt.ylabel("News Category")

plt.tight_layout()
plt.show()

"""# **18. Error Analysis**"""

sample_article = annotation_df[
    "Annotation_Text"
].iloc[0]

spacy_sample = extract_spacy_entities(
    sample_article
)

bert_sample = extract_bert_entities(
    sample_article
)

print("===== spaCy =====")

for entity in spacy_sample:

    print(
        entity["text"],
        "->",
        entity["label"]
    )

print("\n===== BERT =====")

for entity in bert_sample:

    print(
        entity["text"],
        "->",
        entity["label"],
        f"({entity['score']:.3f})"
    )

false_positives_bert = (
    pred_entities_bert -
    true_entities_bert
)

false_negatives_bert = (
    true_entities_bert -
    pred_entities_bert
)

print(
    "BERT False Positives:",
    len(false_positives_bert)
)

print(
    "BERT False Negatives:",
    len(false_negatives_bert)
)

print("\nFalse Positives:")

for entity in list(
    false_positives_bert
)[:20]:

    print(entity)

print("\nFalse Negatives:")

for entity in list(
    false_negatives_bert
)[:20]:

    print(entity)

summary = pd.DataFrame({

    "Metric": [
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "spaCy": [
        precision_spacy,
        recall_spacy,
        f1_spacy
    ],

    "BERT": [
        precision_bert,
        recall_bert,
        f1_bert
    ]
})

summary[
    ["spaCy", "BERT"]
] = summary[
    ["spaCy", "BERT"]
].round(3)

display(summary)

"""# **19. Visualizations**"""

final_results = pd.DataFrame({
    "Model": ["spaCy", "BERT"],
    "Precision": [precision_spacy, precision_bert],
    "Recall": [recall_spacy, recall_bert],
    "F1 Score": [f1_spacy, f1_bert]
})

plot_df = final_results.melt(
    id_vars="Model",
    var_name="Metric",
    value_name="Score"
)

plt.figure(figsize=(9, 5))

sns.barplot(
    data=plot_df,
    x="Metric",
    y="Score",
    hue="Model"
)

plt.title(
    "spaCy vs BERT NER Performance"
)

plt.ylim(0, 1)

plt.show()

print(annotation_df.columns.tolist())
print(annotation_df["Manual_Entities"].head())
print(annotation_df["Manual_Entities"].notna().sum())
print(annotation_df["Annotation_Text"].notna().sum())

"""# **20. Conclusion**

This project developed an end-to-end Named Entity Recognition pipeline
using real-world news articles from the Kaggle News Articles Classification
Dataset.

The pipeline used text preprocessing, sentence segmentation and two
pretrained NER approaches: spaCy and BERT-based NER.

A manually verified evaluation subset consisting of 20 news articles was
created using the first 3,000 characters of each article. spaCy predictions
were used as candidate annotations and were manually checked and corrected
to create the ground-truth labels.

Precision, Recall and F1-Score were calculated to quantitatively evaluate
the NER models. Entity distribution, news-category differences, confidence
scores and model errors were also analyzed.

The analysis demonstrates how pretrained NLP models can automatically
extract structured information such as people, organizations, locations,
dates and other entities from unstructured news text.

The main limitations include the relatively small manually annotated
evaluation subset, possible annotation errors, ambiguity in entity names,
and differences between the news domain and the data used to train the
pretrained models.
"""